---
title: "Kaggel"
author: "Gil Omer & Doron Zamir"
date: "6/19/2021"
output:
  html_document:
    html_preview: true
    toc: true 
    toc_float: true
    theme: readable
    highlight: breezedark
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  eval = TRUE,
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  cache = FALSE,
  dev = "svglite",
  fig.ext = ".svg")
```

# Getting Ready

## Load Packages

```{r load_pack}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  tidyverse,
  magritrr,
  tidymodels,
  DataExplorer,
  GGally,
  rpart,
  broom
)
```

## Load Data

```{r}
data_raw <- read.csv("Data/train.csv")
test_raw <- read.csv("Data/test.csv")
set.seed(1991)
```

## Initial Split

```{r}
wage_split <- initial_split(data_raw, prop = 0.75, strata = lnwage)
wage_train <- training(wage_split)
wage_test <- testing(wage_split)

```

### CV Fold

```{r}
wage_folds <- wage_train %>% 
  vfold_cv(v=5)
```

# Benchmark Model

## Basic Recipe

```{r}
base_rec <-
  recipe(lnwage ~., data = wage_train) %>% 
  update_role(ID, new_role = "ID") %>% 
  step_bin2factor(all_predictors(), -starts_with("exp"), -"edyrs" ) %>%
  step_mutate(age = edyrs + expf + expp) %>%
  step_poly(age, degree = tune("lambda")) %>%
  step_center(all_predictors(), - all_nominal()) %>%
  step_scale(all_predictors(), - all_nominal()) %>%
  step_dummy(all_nominal()) %>%
  step_zv(all_predictors())

```

## Set Linear Models

```{r}
lm_spec <- linear_reg() %>% 
  set_args(penalty = tune(), mixture = 1, nlambadas = 10) %>% 
  set_engine("glmnet") %>% 
  set_mode("regression")
```

## Workflow

```{r}
basic_wkflw <- 
  workflow() %>% 
  add_recipe(base_rec) %>% 
  add_model(lm_spec)

```

## Tune

```{r}
basic_lm_reuslts <- basic_wkflw %>% 
  tune_grid(
    resamples= wage_folds
  )

basic_lm_reuslts %>% show_best(
  metric = "rmse"
)
```
